### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by McSinyx** [McSinyx/slacker-game#1]
Dear @hanclinto, I think you are the original author of this game. Do you think it's OK to re-license the game to GPLv3+? Thanks a lot for creating this elegant thing, in one day 😜

**Comment by ClintTCG** [comment]
Sure!  I'm totally amazed anyone still remembers this -- this was a really fun project, and I'm happy to see you have put it up here!  I think I originally may have licensed it under BSD or Public Domain licensing -- that's how I normally roll.  I'm fine with it being licensed however you see fit. :)  

Thanks for asking!

**Comment by HanClinto** [comment]
Sure! I'm totally amazed anyone still remembers this -- this was a really fun project, and I'm happy to see you have put it up here! I think I originally may have licensed it under BSD or Public Domain licensing -- that's how I normally roll. I'm fine with it being licensed however you see fit. :)

Thanks for asking!

**Comment by HanClinto** [comment]
I just read through your code changes and everything -- it all looks really good!  I'm very impressed you were able to decipher my code given the lack of comments.  You did a great job making optimizations and making the code cleaner -- I really like everything you did.  Thanks for moving this forward!  :)

**Comment by McSinyx** [comment]
> I think I originally may have licensed it under BSD or Public Domain licensing

I hope it's public domain, as I'm not sure if one can relicense from BSD to GPL (I'm a complete noob on these legal stuffs). Also on [the pygame page](http://www.pygame.org/project-Slacker-402-.html) you wrote:

> This game, its source code, and graphics, are freely available for modification as well as use in private, commercial, or open-source projects. Credit is appreciated, but not necessary. We hope you have fun and learn something.

About the refactoring thing, I'm not doing a very nice job actually 😉 I make bugs on every commit but eh, hide the small fix on the next commit message (I'm aware that these messages can be as long as we want, but maybe I'm embarrass about those random bug - bad practice though). And talking about something impressive, your game run flawlessly on both Python 2 and 3 on my GNU/Linux machine despite tha fact that it was last tested 10 years ago only on Windows and Mac. Thank you very much for making this.

**Comment by McSinyx** [comment]
There is [one part](https://github.com/McSinyx/slacker-game/blob/a58fa656a49ddad5f52e7ede4ef75590d871608d/slacker-game#L218) that I don't understand:

```python
deltaT = (pygame.time.get_ticks() - lt[2]) * 0.008 # How long it has been falling
y = lt[1]*TILE_HEIGHT + deltaT*deltaT
```

Why do the time delta get multiplied by 0.008 and then squared?

**Comment by HanClinto** [comment]
Yeah, looks like that licensing language I used is pretty darn close to Public Domain.  Regardless, you've got explicit permission to re-license now, so that's moot. :)  Any sort of license you choose is fine with me.

As far as your question... geeze that is dirty code of mine.  But I think I can explain. :)  

The 0.008 is a scaling factor that functions a bit like a gravitational constant.  We square deltaT so that the block falls with exponentially increasing speed -- looking very similar to an object falling by gravity.  

This is essentially following Newton's Equations of motion -- just a stripped down version of Equation #5 from here: 
https://en.wikipedia.org/wiki/Equations_of_motion#Constant_translational_acceleration_in_a_straight_line

The full equation would say something like:

`currentPosition = initialPosition + initialVelocity * time + 0.5 * gravity * time^2`

Because initialVelocity is zero, then Newton's equation of motion just reduces to:

`currentPosition = initialPosition + initialVelocity * time + 0.5 * gravity * time^2`

I had consolidated that 0.5 and gravitational constant into the 0.008 that I was multiplying to the deltaT calculation, and that was confusing things, because 0.008 shouldn't apply to time at all.  

If I were to refactor it, I would make Lost Tile into an object with named members (rather than just a tuple with indices) and write it something like:

```python
deltaT = (pygame.time.get_ticks() - lt.start_time)
G = 0.000064     # Gravitational constant to control speed of descent
y = lt.start_height*TILE_HEIGHT + deltaT*deltaT*G
```

Clear as mud? :)

**Comment by McSinyx** [comment]
Thanks a lot for the explicit permission! 🙇 

> We square deltaT so that the block falls with exponentially increasing speed -- looking very similar to an object falling by gravity.

I didn't recognize the equation 😛 I guess that's a trick and `0.008` is a constant related to `SCREEN_SIZE`.

> If I were to refactor it, I would make Lost Tile into an object with named members (rather than just a tuple with indices)

I've already done that in the commit before the latest one. Now I think I'll write a method and choose a constant that if I'll be able to support resizable window, the motion will look the same.

Thank you very much for spending time helping me. BTW I'm just a high school student with limited knowledge and English skill (somehow when I read my comments, they always sound rude).
